name: Selenium IDE Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
        
    - name: Install nuget packages(dependencies)
      run: dotnet restore
      
    - name: build
      run: dotnet build --no-restore
      
    - name: Run tests
      run: dotnet test